<?php

date_default_timezone_set('Asia/Kolkata');
include("../includes/config.php");
include("../includes/dbConfigConn.php");
include("../includes/dbRptConn.php");
include("../includes/constantsVals.php");
include("../includes/genFunctions.php");
include("rptGenFunctions.php");
require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/mailFunction.php';

class CustomTCPDF extends TCPDF {
  public function Header() {
  }

  public function Footer() {
    $this->SetFont('times', '', 12);
    $this->SetY(-12);
    $this->Cell(277, 7, 'Page # ' . $this->getAliasNumPage(), 'T', false, 'R');
  }
}// end of customTPPDF

//if ($debugFlag) { $funcStartTime = microtime(true); }

$sensorConfigData=[];
$deviceConfigData=[];
$namesConfigData=[];
$firmwareDataArray=[];

//this will read all the configuration of sensor from the prefetched file.
//readConfigFiles();

readLocationConfigDB();
readDeviceConfigDB();
readSensorConfigDB();

$fromDateIn='';
$toDateIn='';
$userEmail='';
$sendEmail='';

$locationID='';
$branchID='';
$facilityID='';
$buildingID='';
$floorID='';
$zoneID='';
$deviceID='';


extract($_GET);

if ($sendEmail == "YES"){
  if ($userEmail == '') {
    $data = array(
      'status' => 'error',
      'msg' => 'User Email not given to send Email',
  );
  $jsonString = json_encode($data);
  header('Content-Type: application/json');
  echo $jsonString;
  return ;
  }
}

if ($deviceID == 'all') {
  $deviceID='';
}

$filters = array_filter([
  "id" => $deviceID,
  "locationID" => $locationID,
  "branchID" => $branchID,
  "facilityID" => $facilityID,
  "buildingID" => $buildingID,
  "floorID" => $floorID,
  "zoneID" => $zoneID
]);

$sql = "SELECT id, locationID, branchID, facilityID, buildingID, floorID, zoneID, deviceName, firmwareVersion, hardwareModelVersion, modifiedBy, modifiedStatus, modifiedAt FROM `devices`";

$count = 0;
if(!empty($filters)){
  foreach ($filters as $key => $value) {
    $condition = "AND";

    if($count == 0){
      $condition = "WHERE";  
    }

    $sql = $sql." $condition $key = '$value' ";
    $count++;
  }
}

$sql = "$sql ORDER BY zoneID, id DESC";

// echo $sql;
// exit;


// if ($deviceID == '' || $deviceID == 'all') {
//   $sql = "SELECT id, locationID, branchID, facilityID, buildingID, floorID, zoneID, deviceName, firmwareVersion, hardwareModelVersion, modifiedBy, modifiedStatus, modifiedAt FROM `devices` ORDER BY zoneID, id DESC";
// }
// else {
//   $sql = "SELECT id, locationID, branchID, facilityID, buildingID, floorID, zoneID, deviceName, firmwareVersion, hardwareModelVersion, modifiedBy, modifiedStatus, modifiedAt FROM `devices` where id = '$deviceID' ORDER BY id DESC";
// }

$getResult = mysqli_query($dbConfigConn,$sql) or die(mysqli_error($dbConfigConn));
if ($getResult->num_rows <= 0) { 
  //echo '<br/>***No processing as now rows for '.$firmwareInfo['concatEmail'];
  $data = array(
      'status' => 'error',
      'msg' => 'No Records Found for display',
  );
  $jsonString = json_encode($data);
  header('Content-Type: application/json');
  echo $jsonString;
  return ;
}

while ($result = mysqli_fetch_assoc($getResult))
{
  $firmwareDataArray[] = $result;
}



createFirmwarePdf($firmwareDataArray, $userEmail, $sendEmail);

function createFirmwarePdf($firmwareDataArray, $userEmail, $sendEmail){
  global $dbConfigConn;
  global $namesConfigData;
  global $deviceConfigData;

  $reportGeneratedBy= 'Auto Generated by System';
  if ($userEmail != '') {
    $reportGeneratedBy=$userEmail;
  }

  $dateObj = new DateTime();
  $reportTime = $dateObj->format(REPORT_DATE_TIME_FORMAT);

  $olderZoneID = '';
  $varHTML='';

  $pdf = new CustomTCPDF(); // Create TCPDF instance
  $pdf->SetPageOrientation('P');
  $pdf->SetFont('times', '', 12);

  $rowCountColorInfo=0;
  foreach ( $firmwareDataArray as $firmwareData ) 
  {
    $rowCountColorInfo++;
    if ($olderZoneID != $firmwareData['zoneID']) {
      if($varHTML!='') {
        $rowCountColorInfo=1;
        $varHTML .= '</tbody></table></body></html>';
        $pdf->AddPage();
        // Set font
        //var_dump($varHTML);
        
        $pdf->writeHTML($varHTML, true, false, true, false, '');
        
      }

      $olderZoneID = $firmwareData['zoneID'];

      //New Zone Create header
      $companyName = $namesConfigData['company']['companyName'];
      $locationName = $namesConfigData['locations'][$firmwareData['locationID']]['locationName'];
      $branchName = $namesConfigData['branches'][$firmwareData['branchID']]['branchName'];
      $facilityName = $namesConfigData['facilities'][$firmwareData['facilityID']]['facilityName'];
      $buildingName = $namesConfigData['buildings'][$firmwareData['buildingID']]['buildingName'];
      $floorName = $namesConfigData['floors'][$firmwareData['floorID']]['floorName'];
      $zoneName = $namesConfigData['zones'][$firmwareData['zoneID']]['zoneName'];

      $varHTML =  '<!DOCTYPE html><html><head><style>table {
        border-collapse: collapse;
        width: 100%;
        }
        th, td {
          border: 1px solid #ccc; 
          padding: 6px;
        }
        </style>
        </head>
        <body>
        <div><table cellspacing="0" cellpadding="2" border="1" style="width:100%; ">
              <tr style="color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.';">
              <td colspan="4" style=" color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.'; text-align: center;"><b>'.FIRMWARE_VERSION_REPORT_NAME.'</b></td>
            </tr>
            <tbody>
          <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
              <td width="20%" >Organization Name</td>
              <td width="32%" >'.$companyName.'</td>
              <td width="22%">Report Taken by</td>
              <td width="26%">'.$reportGeneratedBy.'</td>
                </tr>
                <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
                  <td >Location</td>
                  <td >'.$locationName.'</td>
                  <td >Report Date & Time</td>
                  <td >'.$reportTime.'</td>
                </tr>
                  <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
                  <td >Branch</td>
                  <td >'.$branchName.'</td>
                  <td colspan="2" rowspan="5"></td>
                </tr>
                <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
                  <td >Facility</td>
                  <td >'.$facilityName.'</td>
                </tr>
                <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
                  <td >Building</td>
                  <td >'.$buildingName.'</td>
                </tr>
                <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
                  <td >Floor</td>
                  <td >'.$floorName.'</td>
                </tr>
                <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
                  <td >Zone</td>
                  <td >'.$zoneName.'</td>
                </tr>
              </tbody>
              </table></div>'; 

              $varHTML .=  '<div><table cellspacing="0" cellpadding="2" border="1" style="width:100%; ">
              <tr>
                  <td style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; color='.REPORT_HEADER_FONT_COLOR.'; " ><b>Date and Time</b></td>
                  <td style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; color='.REPORT_HEADER_FONT_COLOR.'; " ><b>Device Name</b></td>
                  <td style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; color='.REPORT_HEADER_FONT_COLOR.'; " ><b>Model No</b></td>
                  <td style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; color='.REPORT_HEADER_FONT_COLOR.'; " ><b>Firmware Version</b></td>
                  <td style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; color='.REPORT_HEADER_FONT_COLOR.'; " ><b>User</b></td>
                  <td style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; color='.REPORT_HEADER_FONT_COLOR.'; " ><b>Status</b></td>
              </tr>
              <tbody>' ;
    }
  
    $cellColor = REPORT_ALTERNATIVE_ROW_COLOR_ONE;
    if (($rowCountColorInfo %2) == 0) {
      $cellColor = REPORT_ALTERNATIVE_ROW_COLOR_TWO;
    }

    $deviceID = $firmwareData['id'];
    if (! isset($deviceConfigData[$deviceID])) {
      continue;
    }
    $deviceTag = $deviceConfigData[$deviceID]['deviceName'];

    $dateObj = new DateTime($firmwareData['modifiedAt']);
    $dateString = $dateObj->format(REPORT_DATE_TIME_FORMAT);

    $varHTML .= '<tr style="background-color: '.$cellColor.';">
            <td style=" text-align: center;"  >'.$dateString.'</td>
            <td style=" text-align: center;"  >'.$deviceTag.'</td>
            <td style=" text-align: center;"  >'.$firmwareData['hardwareModelVersion'].'</td>
            <td style=" text-align: center;"  >'.$firmwareData['firmwareVersion'].'</td>
            <td style=" text-align: center;"  >'.'-'.'</td>
            <td style=" text-align: center;"  >'.'-'.'</td>
          </tr>'; 
          
  }

  if ($varHTML!='') {
    $varHTML .= '</tbody></table></body></html>';
    
    $pdf->AddPage();
    // Set font
    $pdf->writeHTML($varHTML, true, false, true, false, '');
  }

  $rnd = rand(100, 999);
  $fileDisplayName = 'Firmware Version Report.pdf';
  $pdfPath = BASE_FILE_PATH_REPORTS.'/firmwareVersionReport_'.$rnd.'.pdf';
  $pdf->Output($pdfPath, 'F');

  //call email and send email. 
  if ($sendEmail == "YES"){
    $tag='';
    // if ($deviceID != '') {
    //   $tag = $deviceConfigData[$deviceID]['deviceName'];
    // }
    sendReportEmails(FIRMWARE_REPORT, $pdfPath, $fileDisplayName, $tag, ' ', ' ' ,$userEmail);
    
    $data = array(
        'status' => 'success',
        'Msg' => 'Email Sent',
    );
    $jsonString = json_encode($data);
    header('Content-Type: application/json');
    echo $jsonString;
    return ;
  }

  header('Content-Type: application/pdf');
  header('Content-Disposition: attachment; filename="Firmware Version Report.pdf"');
  header('Content-Length: ' . filesize($pdfPath));
  readfile($pdfPath);

}



//if ($debugFlag) { $funcEndTime = microtime(true); echo "\n<br/>\n[".__FILE__."]-Time St [$funcStartTime] End [$funcEndTime] Exec[".($funcEndTime - $funcStartTime)."]"; }             

?>