<?php

function getAqiRptHeader($zoneID, $fromDateIn, $toDateIn, $userEmail) {
    global $sensorConfigData;
    global $deviceConfigData;
    global $namesConfigData;

    $varHTML='';
    if ($zoneID==''){
        return;
    }
    $reportGeneratedBy = 'Auto Generated by System';

    $dateObj = new DateTime($fromDateIn);
    $fromDateIn = $dateObj->format(REPORT_DATE_FORMAT);

    $dateObj = new DateTime($toDateIn);
    $toDateIn = $dateObj->format(REPORT_DATE_FORMAT);

    if ( $userEmail != '' ){
        $reportGeneratedBy=$userEmail;
    }

    $locationID = $namesConfigData['zones'][$zoneID]['locationID'];
    $branchID = $namesConfigData['zones'][$zoneID]['branchID'];
    $facilityID = $namesConfigData['zones'][$zoneID]['facilityID'];
    $buildingID = $namesConfigData['zones'][$zoneID]['buildingID'];
    $floorID = $namesConfigData['zones'][$zoneID]['floorID'];
    
    $companyName = $namesConfigData['company']['companyName'];
    $locationName = $namesConfigData['locations'][$locationID]['locationName'];
    $branchName = $namesConfigData['branches'][$branchID]['branchName'];
    $facilityName = $namesConfigData['facilities'][$facilityID]['facilityName'];
    $buildingName = $namesConfigData['buildings'][$buildingID]['buildingName'];
    $floorName = $namesConfigData['floors'][$floorID]['floorName'];
    $zoneName = $namesConfigData['zones'][$zoneID]['zoneName'];
    
    $varHTML =  '<!DOCTYPE html><html><head><style>table {
        border-collapse: collapse;
        width: 100%;
        }
        th, td {
          border: 1px solid #ccc; 
          padding: 6px;
        }
        </style>
        </head>
        <body><div><table cellspacing="0" cellpadding="2" border="1" style="width:100%; "><thead>
              <tr style="color: '.REPORT_HEADER_FONT_COLOR.';  background-color: '.REPORT_HEADER_COLOR.';">
              <td colspan="4" style=" color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.'; text-align: center;"><b>'.AQI_REPORT_NAME.'</b></td>
            </tr></thead>
            <tbody>
          <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
                  <td width="20%">Organization Name</td>
                  <td width="30%">'.$companyName.'</td>
                  <td width="20%">From Date</td>
                  <td width="30%">'.$fromDateIn.'</td>
                </tr>
                <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
                  <td >Location</td>
                  <td >'.$locationName.'</td>
                  <td >To Date</td>
                  <td >'.$toDateIn.'</td>
                </tr>
                  <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
                  <td >Branch</td>
                  <td >'.$branchName.'</td>
                  <td >Report Taken By</td>
                  <td >'.$reportGeneratedBy.'</td>
                </tr>
                <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
                  <td >Facility</td>
                  <td >'.$facilityName.'</td>
                  <td >Report Date Time</td>
                  <td >'.date(REPORT_DATE_TIME_FORMAT).'</td>
                </tr>
                <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
                  <td >Building</td>
                  <td >'.$buildingName.'</td>
                  <td colspan="2" rowspan="3"></td>
                </tr>
                <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
                  <td >Floor</td>
                  <td >'.$floorName.'</td>
                </tr>
                <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
                  <td >Zone</td>
                  <td >'.$zoneName.'</td>
                </tr>
              </tbody>
              </table></div>';

    return $varHTML;
}


function limitEditLogRptHeader($deviceID, $fromDateIn, $toDateIn, $userEmail) {
  global $sensorConfigData;
  global $deviceConfigData;
  global $namesConfigData;

  $varHTML='';
  if ($deviceID==''){
      return;
  }
  $reportGeneratedBy = 'Auto Generated by System';

  $dateObj = new DateTime($fromDateIn);
  $fromDateIn = $dateObj->format(REPORT_DATE_FORMAT);

  $dateObj = new DateTime($toDateIn);
  $toDateIn = $dateObj->format(REPORT_DATE_FORMAT);

  if ( $userEmail != '' ){
      $reportGeneratedBy=$userEmail;
  }

  $companyName = isset($namesConfigData['company']['companyName']) ? $namesConfigData['company']['companyName'] : '';
  $locationName = isset($deviceConfigData[$deviceID]['locationID']) && isset($namesConfigData['locations'][$deviceConfigData[$deviceID]['locationID']]['locationName']) ? $namesConfigData['locations'][$deviceConfigData[$deviceID]['locationID']]['locationName'] : '';
  $branchName = isset($deviceConfigData[$deviceID]['branchID']) && isset($namesConfigData['branches'][$deviceConfigData[$deviceID]['branchID']]['branchName']) ? $namesConfigData['branches'][$deviceConfigData[$deviceID]['branchID']]['branchName'] : '';
  $facilityName = isset($deviceConfigData[$deviceID]['facilityID']) && isset($namesConfigData['facilities'][$deviceConfigData[$deviceID]['facilityID']]['facilityName']) ? $namesConfigData['facilities'][$deviceConfigData[$deviceID]['facilityID']]['facilityName'] : '';
  $buildingName = isset($deviceConfigData[$deviceID]['buildingID']) && isset($namesConfigData['buildings'][$deviceConfigData[$deviceID]['buildingID']]['buildingName']) ? $namesConfigData['buildings'][$deviceConfigData[$deviceID]['buildingID']]['buildingName'] : '';
  $floorName = isset($deviceConfigData[$deviceID]['floorID']) && isset($namesConfigData['floors'][$deviceConfigData[$deviceID]['floorID']]['floorName']) ? $namesConfigData['floors'][$deviceConfigData[$deviceID]['floorID']]['floorName'] : '';
  $zoneName = isset($deviceConfigData[$deviceID]['zoneID']) && isset($namesConfigData['zones'][$deviceConfigData[$deviceID]['zoneID']]['zoneName']) ? $namesConfigData['zones'][$deviceConfigData[$deviceID]['zoneID']]['zoneName'] : '';
  $deviceName = isset($deviceConfigData[$deviceID]['deviceName']) ? $deviceConfigData[$deviceID]['deviceName'] : '';
  
  
  $varHTML =  '<!DOCTYPE html><html><head><style>table {
    border-collapse: collapse;
    width: 100%;
    }
    th, td {
      border: 1px solid #ccc; 
      padding: 6px;
    }
    </style>
    </head>
    <body><div><table cellspacing="0" cellpadding="2" border="1" style="width:100%; "><thead>
          <tr style="color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.';">
          <td colspan="4" style=" color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.'; text-align: center;"><b>'.LIMIT_EDIT_LOG_REPORT_NAME.'</b></td>
        </tr></thead>
        <tbody>
      <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
              <td width="20%" >Organization Name</td>
              <td width="32%" >'.$companyName.'</td>
              <td width="22%">From Date</td>
              <td width="26%">'.$fromDateIn.'</td>
            </tr>
            <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
              <td >Location</td>
              <td >'.$locationName.'</td>
              <td >To Date</td>
              <td >'.$toDateIn.'</td>
            </tr>
              <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
              <td >Branch</td>
              <td >'.$branchName.'</td>
              <td >Report Taken By</td>
              <td >'.$reportGeneratedBy.'</td>
            </tr>
            <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
              <td >Facility</td>
              <td >'.$facilityName.'</td>
              <td >Report Date & Time</td>
              <td >'.date(REPORT_DATE_TIME_FORMAT).'</td>
            </tr>
            <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
              <td >Building</td>
              <td >'.$buildingName.'</td>
              <td colspan="2" rowspan="4"></td>
            </tr>
            <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
              <td >Floor</td>
              <td >'.$floorName.'</td>
            </tr>
            <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
              <td >Zone</td>
              <td >'.$zoneName.'</td>
            </tr>
            
          </tbody>
          </table></div>';

          $varHTML .=  '<div><table cellspacing="0" cellpadding="2" border="1" style="width:100%; ">
          <thead>
            <tr style="background-color: '.REPORT_HEADER_COLOR.';">
              <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="14.3%"><b>Date and Time</b></th>
              <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="14.3%"><b>User</b></th>
              <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="14.3%"><b>Device</b></th>
              <th style="color: '.REPORT_HEADER_FONT_COLOR.';  text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="14.3%"><b>SensorName</b></th>
              <th style="color: '.REPORT_HEADER_FONT_COLOR.';  text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="14.3%"><b>Limit</b></th>
              <th style="color: '.REPORT_HEADER_FONT_COLOR.';  text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="14.3%"><b>Old</b></th>
              <th style="color: '.REPORT_HEADER_FONT_COLOR.';  text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="14.3%"><b>New</b></th>

              
            </tr>
          </thead>
          <tbody>';

          return $varHTML;
}


function getSensorRptHeader($deviceID, $fromDateIn, $toDateIn, $userEmail) {
    global $sensorConfigData;
    global $deviceConfigData;
    global $namesConfigData;

    $varHTML='';
    if ($deviceID==''){
        return;
    }
    $reportGeneratedBy = 'Auto Generated by System';

    $dateObj = new DateTime($fromDateIn);
    $fromDateIn = $dateObj->format(REPORT_DATE_FORMAT);

    $dateObj = new DateTime($toDateIn);
    $toDateIn = $dateObj->format(REPORT_DATE_FORMAT);

    if ( $userEmail != '' ){
        $reportGeneratedBy=$userEmail;
    }

    $companyName = isset($namesConfigData['company']['companyName']) ? $namesConfigData['company']['companyName'] : '';
    $locationName = isset($deviceConfigData[$deviceID]['locationID']) && isset($namesConfigData['locations'][$deviceConfigData[$deviceID]['locationID']]['locationName']) ? $namesConfigData['locations'][$deviceConfigData[$deviceID]['locationID']]['locationName'] : '';
    $branchName = isset($deviceConfigData[$deviceID]['branchID']) && isset($namesConfigData['branches'][$deviceConfigData[$deviceID]['branchID']]['branchName']) ? $namesConfigData['branches'][$deviceConfigData[$deviceID]['branchID']]['branchName'] : '';
    $facilityName = isset($deviceConfigData[$deviceID]['facilityID']) && isset($namesConfigData['facilities'][$deviceConfigData[$deviceID]['facilityID']]['facilityName']) ? $namesConfigData['facilities'][$deviceConfigData[$deviceID]['facilityID']]['facilityName'] : '';
    $buildingName = isset($deviceConfigData[$deviceID]['buildingID']) && isset($namesConfigData['buildings'][$deviceConfigData[$deviceID]['buildingID']]['buildingName']) ? $namesConfigData['buildings'][$deviceConfigData[$deviceID]['buildingID']]['buildingName'] : '';
    $floorName = isset($deviceConfigData[$deviceID]['floorID']) && isset($namesConfigData['floors'][$deviceConfigData[$deviceID]['floorID']]['floorName']) ? $namesConfigData['floors'][$deviceConfigData[$deviceID]['floorID']]['floorName'] : '';
    $zoneName = isset($deviceConfigData[$deviceID]['zoneID']) && isset($namesConfigData['zones'][$deviceConfigData[$deviceID]['zoneID']]['zoneName']) ? $namesConfigData['zones'][$deviceConfigData[$deviceID]['zoneID']]['zoneName'] : '';
    $deviceName = isset($deviceConfigData[$deviceID]['deviceName']) ? $deviceConfigData[$deviceID]['deviceName'] : '';
    
    
    $varHTML =  '<!DOCTYPE html><html><head><style>table {
      border-collapse: collapse;
      width: 100%;
      }
      th, td {
        border: 1px solid #ccc; 
        padding: 6px;
      }
      </style>
      </head>
      <body><div><table cellspacing="0" cellpadding="2" border="1" style="width:100%; "><thead>
            <tr style="color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.';">
            <td colspan="4" style=" color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.'; text-align: center;"><b>'.SENSOR_STATUS_REPORT_NAME.'</b></td>
          </tr></thead>
          <tbody>
        <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
                <td width="20%" >Organization Name</td>
                <td width="32%" >'.$companyName.'</td>
                <td width="22%">From Date</td>
                <td width="26%">'.$fromDateIn.'</td>
              </tr>
              <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
                <td >Location</td>
                <td >'.$locationName.'</td>
                <td >To Date</td>
                <td >'.$toDateIn.'</td>
              </tr>
                <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
                <td >Branch</td>
                <td >'.$branchName.'</td>
                <td >Report Taken By</td>
                <td >'.$reportGeneratedBy.'</td>
              </tr>
              <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
                <td >Facility</td>
                <td >'.$facilityName.'</td>
                <td >Report Date & Time</td>
                <td >'.date(REPORT_DATE_TIME_FORMAT).'</td>
              </tr>
              <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
                <td >Building</td>
                <td >'.$buildingName.'</td>
                <td colspan="2" rowspan="4"></td>
              </tr>
              <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
                <td >Floor</td>
                <td >'.$floorName.'</td>
              </tr>
              <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
                <td >Zone</td>
                <td >'.$zoneName.'</td>
              </tr>
              <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
                <td >Device</td>
                <td >'.$deviceName.'</td>
              </tr>
            </tbody>
            </table></div>';

            $varHTML .=  '<div><table cellspacing="0" cellpadding="2" border="1" style="width:100%; ">
            <thead>
              <tr style="background-color: '.REPORT_HEADER_COLOR.';">
                <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="10%"><b>Date</b></th>
                <th style="color: '.REPORT_HEADER_FONT_COLOR.';  text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="38%"><b>Sensor Name</b></th>
                <th style="color: '.REPORT_HEADER_FONT_COLOR.';  text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="13%"><b>MIN</b></th>
                <th style="color: '.REPORT_HEADER_FONT_COLOR.';  text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="13%"><b>MAX</b></th>
                <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="13%"><b>AVG</b></th>
                <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="13%"><b>STATUS</b></th>
              </tr>
            </thead>
            <tbody>';

            return $varHTML;
}


function getCalibrationRptHeader($deviceID, $fromDateIn, $toDateIn, $userEmail) {
  global $sensorConfigData;
  global $deviceConfigData;
  global $namesConfigData;

  $varHTML='';
  if ($deviceID==''){
      return;
  }
  $reportGeneratedBy = 'Auto Generated by System';

  $dateObj = new DateTime($fromDateIn);
  $fromDateIn = $dateObj->format(REPORT_DATE_FORMAT);

  $dateObj = new DateTime($toDateIn);
  $toDateIn = $dateObj->format(REPORT_DATE_FORMAT);

  if ( $userEmail != '' ){
      $reportGeneratedBy=$userEmail;
  }

  $companyName = isset($namesConfigData['company']['companyName']) ? $namesConfigData['company']['companyName'] : '';
  $locationName = isset($deviceConfigData[$deviceID]['locationID']) && isset($namesConfigData['locations'][$deviceConfigData[$deviceID]['locationID']]['locationName']) ? $namesConfigData['locations'][$deviceConfigData[$deviceID]['locationID']]['locationName'] : '';
  $branchName = isset($deviceConfigData[$deviceID]['branchID']) && isset($namesConfigData['branches'][$deviceConfigData[$deviceID]['branchID']]['branchName']) ? $namesConfigData['branches'][$deviceConfigData[$deviceID]['branchID']]['branchName'] : '';
  $facilityName = isset($deviceConfigData[$deviceID]['facilityID']) && isset($namesConfigData['facilities'][$deviceConfigData[$deviceID]['facilityID']]['facilityName']) ? $namesConfigData['facilities'][$deviceConfigData[$deviceID]['facilityID']]['facilityName'] : '';
  $buildingName = isset($deviceConfigData[$deviceID]['buildingID']) && isset($namesConfigData['buildings'][$deviceConfigData[$deviceID]['buildingID']]['buildingName']) ? $namesConfigData['buildings'][$deviceConfigData[$deviceID]['buildingID']]['buildingName'] : '';
  $floorName = isset($deviceConfigData[$deviceID]['floorID']) && isset($namesConfigData['floors'][$deviceConfigData[$deviceID]['floorID']]['floorName']) ? $namesConfigData['floors'][$deviceConfigData[$deviceID]['floorID']]['floorName'] : '';
  $zoneName = isset($deviceConfigData[$deviceID]['zoneID']) && isset($namesConfigData['zones'][$deviceConfigData[$deviceID]['zoneID']]['zoneName']) ? $namesConfigData['zones'][$deviceConfigData[$deviceID]['zoneID']]['zoneName'] : '';
  $deviceName = isset($deviceConfigData[$deviceID]['deviceName']) ? $deviceConfigData[$deviceID]['deviceName'] : '';
  
  
  $varHTML =  '<!DOCTYPE html><html><head><style>table {
    border-collapse: collapse;
    width: 100%;
    }
    th, td {
      border: 1px solid #ccc; 
      padding: 6px;
    }
    </style>
    </head>
    <body><div><table cellspacing="0" cellpadding="2" border="1" style="width:100%; "><thead>
          <tr style="color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.';">
          <td colspan="4" style=" color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.'; text-align: center;"><b>'.CALIBRATION_REPORT_NAME.'</b></td>
        </tr></thead>
        <tbody>
      <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
              <td width="20%" >Organization Name</td>
              <td width="32%" >'.$companyName.'</td>
              <td width="22%">From Date</td>
              <td width="26%">'.$fromDateIn.'</td>
            </tr>
            <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
              <td >Location</td>
              <td >'.$locationName.'</td>
              <td >To Date</td>
              <td >'.$toDateIn.'</td>
            </tr>
              <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
              <td >Branch</td>
              <td >'.$branchName.'</td>
              <td >Report Taken By</td>
              <td >'.$reportGeneratedBy.'</td>
            </tr>
            <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
              <td >Facility</td>
              <td >'.$facilityName.'</td>
              <td >Report Date & Time</td>
              <td >'.date(REPORT_DATE_TIME_FORMAT).'</td>
            </tr>
            <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
              <td >Building</td>
              <td >'.$buildingName.'</td>
              <td colspan="2" rowspan="4"></td>
            </tr>
            <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
              <td >Floor</td>
              <td >'.$floorName.'</td>
            </tr>
            <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
              <td >Zone</td>
              <td >'.$zoneName.'</td>
            </tr>
            <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
              <td >Device</td>
              <td >'.$deviceName.'</td>
            </tr>
          </tbody>
          </table></div>';

          $varHTML .=  '<div><table cellspacing="0" cellpadding="2" border="1" style="width:100%; ">
          <thead>
            <tr style="background-color: '.REPORT_HEADER_COLOR.';">
              <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="13%"><b>Date and Time</b></th>
              <th style="color: '.REPORT_HEADER_FONT_COLOR.';  text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="10%"><b>Device</b></th>
              <th style="color: '.REPORT_HEADER_FONT_COLOR.';  text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="13%"><b>Sensor Name</b></th>
              <th style="color: '.REPORT_HEADER_FONT_COLOR.';  text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="13%"><b>Calibration Due Date </b></th>
              <th style="color: '.REPORT_HEADER_FONT_COLOR.';  text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="13%"><b>Calibrated Date </b></th>
              <th style="color: '.REPORT_HEADER_FONT_COLOR.';  text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="9%"><b>Result</b></th>
              <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="13%"><b>Next Calibrartion Due Date</b></th>
              <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="16%"><b>User Email</b></th>
            </tr>
          </thead>
          <tbody>';

          return $varHTML;
}


function getBumpTestRptHeader($deviceID, $fromDateIn, $toDateIn, $userEmail) {
  global $sensorConfigData;
  global $deviceConfigData;
  global $namesConfigData;

  $varHTML='';
  if ($deviceID==''){
      return;
  }
  $reportGeneratedBy = 'Auto Generated by System';

  $dateObj = new DateTime($fromDateIn);
  $fromDateIn = $dateObj->format(REPORT_DATE_FORMAT);

  $dateObj = new DateTime($toDateIn);
  $toDateIn = $dateObj->format(REPORT_DATE_FORMAT);

  if ( $userEmail != '' ){
      $reportGeneratedBy=$userEmail;
  }

  $companyName = isset($namesConfigData['company']['companyName']) ? $namesConfigData['company']['companyName'] : '';
  $locationName = isset($deviceConfigData[$deviceID]['locationID']) && isset($namesConfigData['locations'][$deviceConfigData[$deviceID]['locationID']]['locationName']) ? $namesConfigData['locations'][$deviceConfigData[$deviceID]['locationID']]['locationName'] : '';
  $branchName = isset($deviceConfigData[$deviceID]['branchID']) && isset($namesConfigData['branches'][$deviceConfigData[$deviceID]['branchID']]['branchName']) ? $namesConfigData['branches'][$deviceConfigData[$deviceID]['branchID']]['branchName'] : '';
  $facilityName = isset($deviceConfigData[$deviceID]['facilityID']) && isset($namesConfigData['facilities'][$deviceConfigData[$deviceID]['facilityID']]['facilityName']) ? $namesConfigData['facilities'][$deviceConfigData[$deviceID]['facilityID']]['facilityName'] : '';
  $buildingName = isset($deviceConfigData[$deviceID]['buildingID']) && isset($namesConfigData['buildings'][$deviceConfigData[$deviceID]['buildingID']]['buildingName']) ? $namesConfigData['buildings'][$deviceConfigData[$deviceID]['buildingID']]['buildingName'] : '';
  $floorName = isset($deviceConfigData[$deviceID]['floorID']) && isset($namesConfigData['floors'][$deviceConfigData[$deviceID]['floorID']]['floorName']) ? $namesConfigData['floors'][$deviceConfigData[$deviceID]['floorID']]['floorName'] : '';
  $zoneName = isset($deviceConfigData[$deviceID]['zoneID']) && isset($namesConfigData['zones'][$deviceConfigData[$deviceID]['zoneID']]['zoneName']) ? $namesConfigData['zones'][$deviceConfigData[$deviceID]['zoneID']]['zoneName'] : '';
  $deviceName = isset($deviceConfigData[$deviceID]['deviceName']) ? $deviceConfigData[$deviceID]['deviceName'] : '';

  
  $varHTML =  '<!DOCTYPE html><html><head><style>table {
    border-collapse: collapse;
    width: 100%;
    }
    th, td {
      border: 1px solid #ccc; 
      padding: 6px;
    }
    </style>
    </head>
    <body><div><table cellspacing="0" cellpadding="2" border="1" style="width:100%; "><thead>
          <tr style="color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.';">
          <td colspan="4" style=" color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.'; text-align: center;"><b>'.BUMP_TEST_REPORT_NAME.'</b></td>
        </tr></thead>
        <tbody>
      <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
              <td width="20%" >Organization Name</td>
              <td width="32%" >'.$companyName.'</td>
              <td width="22%">From Date</td>
              <td width="26%">'.$fromDateIn.'</td>
            </tr>
            <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
              <td >Location</td>
              <td >'.$locationName.'</td>
              <td >To Date</td>
              <td >'.$toDateIn.'</td>
            </tr>
              <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
              <td >Branch</td>
              <td >'.$branchName.'</td>
              <td >Report Taken By</td>
              <td >'.$reportGeneratedBy.'</td>
            </tr>
            <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
              <td >Facility</td>
              <td >'.$facilityName.'</td>
              <td >Report Date & Time</td>
              <td >'.date(REPORT_DATE_TIME_FORMAT).'</td>
            </tr>
            <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
              <td >Building</td>
              <td >'.$buildingName.'</td>
              <td colspan="2" rowspan="4"></td>
            </tr>
            <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
              <td >Floor</td>
              <td >'.$floorName.'</td>
            </tr>
            <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
              <td >Zone</td>
              <td >'.$zoneName.'</td>
            </tr>
            <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
              <td >Device</td>
              <td >'.$deviceName.'</td>
            </tr>
          </tbody>
          </table></div>';

          $varHTML .=  '<div><table cellspacing="0" cellpadding="2" border="1" style="width:100%; ">
          <thead>
            <tr style="background-color: '.REPORT_HEADER_COLOR.';">
              <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="15.2%"><b>Date and Time</b></th>
              <th style="color: '.REPORT_HEADER_FONT_COLOR.';  text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="14.2%"><b>Device</b></th>
              <th style="color: '.REPORT_HEADER_FONT_COLOR.';  text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="14.2%"><b>SensorName</b></th>
              <th style="color: '.REPORT_HEADER_FONT_COLOR.';  text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="14.2%"><b>Test Type </b></th>
              <th style="color: '.REPORT_HEADER_FONT_COLOR.';  text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="10%"><b>Deviation</b></th>
              <th style="color: '.REPORT_HEADER_FONT_COLOR.';  text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="14.2%"><b>Result</b></th>
              <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="18.2%"><b>User</b></th>
            </tr>
          </thead>
          <tbody>';

          return $varHTML;
}


function getServerUsageRptHeader( $fromDateIn, $toDateIn, $userEmail) {
    global $namesConfigData;

    $varHTML='';
    $reportGeneratedBy = 'Auto Generated by System';

    $dateObj = new DateTime($fromDateIn);
    $fromDateIn = $dateObj->format(REPORT_DATE_FORMAT);

    $dateObj = new DateTime($toDateIn);
    $toDateIn = $dateObj->format(REPORT_DATE_FORMAT);

    if ( $userEmail != '' ){
        $reportGeneratedBy=$userEmail;
    }

    $companyName = $namesConfigData['company']['companyName'];
    $varHTML =  '<!DOCTYPE html><html><head><style>table {
        border-collapse: collapse;
        width: 100%;
        }
        th, td {
          border: 1px solid #ccc; 
          padding: 6px;
        }
        </style>
        </head>
        <body><div><table cellspacing="0" cellpadding="2" border="1" style="width:100%; "><thead>
              <tr style="color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.';">
              <td colspan="4" style="color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.'; text-align: center;"><b>'.SERVER_UTILIZATION_REPORT_NAME.'</b></td>
            </tr></thead>
            <tbody>
          <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
                  <td width="20%">Organization Name</td>
                  <td width="32%">'.$companyName.'</td>
                  <td width="22%">From Date</td>
                  <td width="26%">'.$fromDateIn.'</td>
                </tr>
                <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
                  <td colspan="2" rowspan="3" ></td>
                  <td >To Date</td>
                  <td >'.$toDateIn.'</td>
                </tr>
                  <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
                  <td >Report Taken By</td>
                  <td >'.$reportGeneratedBy.'</td>
                </tr>
                <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
                  <td >Report Date & Time</td>
                  <td >'.date(REPORT_DATE_TIME_FORMAT).'</td>
                </tr>
              </tbody>
              </table></div>';

      $varHTML .=  '<div><table cellspacing="0" cellpadding="2" border="1" style="width:100%; ">
              <thead>
                <tr style="color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.';">
                  <th style=" color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="18%" ><b>Date and Time</b></th>
                  <th style=" color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="30%"><b>Physical Memory</b></th>
                  <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="30%"><b>Disk Usage</b></th>
                  <th style=" color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="11%"><b>Average CPU</b></th>
                  <th style=" color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="11%"><b>Server Load</b></th>
                </tr>
              </thead>
              <tbody>';
  
    return $varHTML;
}


function getEventLogRptHeader( $fromDateIn, $toDateIn, $userEmail) {
  global $namesConfigData;

  $varHTML='';
  $reportGeneratedBy = 'Auto Generated by System';

  $dateObj = new DateTime($fromDateIn);
  $fromDateIn = $dateObj->format(REPORT_DATE_FORMAT);

  $dateObj = new DateTime($toDateIn);
  $toDateIn = $dateObj->format(REPORT_DATE_FORMAT);

  if ( $userEmail != '' ){
      $reportGeneratedBy=$userEmail;
  }

  $companyName = $namesConfigData['company']['companyName'];
  $varHTML =  '<!DOCTYPE html><html><head><style>table {
      border-collapse: collapse;
      width: 100%;
      }
      th, td {
        border: 1px solid #ccc; 
        padding: 6px;
      }
      </style>
      </head>
      <body><div><table cellspacing="0" cellpadding="2" border="1" style="width:100%; "><thead>
            <tr style="background-color: '.REPORT_HEADER_COLOR.';">
            <td colspan="4" style="color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.'; text-align: center;"><b>'.EVENT_LOG_REPORT_NAME.'</b></td>
          </tr></thead>
          <tbody>
        <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
                <td width="20%">Organization Name</td>
                <td width="32%">'.$companyName.'</td>
                <td width="22%">From Date</td>
                <td width="26%">'.$fromDateIn.'</td>
              </tr>
              <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
                <td colspan="2" rowspan="3" ></td>
                <td >To Date</td>
                <td >'.$toDateIn.'</td>
              </tr>
                <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
                <td >Report Taken By</td>
                <td >'.$reportGeneratedBy.'</td>
              </tr>
              <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
                <td >Report Date & Time</td>
                <td >'.date(REPORT_DATE_TIME_FORMAT).'</td>
              </tr>
            </tbody>
            </table></div>';

    $varHTML .=  '<div><table cellspacing="0" cellpadding="2" border="1" style="width:100%; ">
            <thead>
              <tr style="background-color: green;">
              <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.';" width="15%" ><b>Date and Time</b></th>
                <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="25%"><b>Email</b></th>
                <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="15%"><b>Event Name</b></th>
                <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="45%"><b>Event Details</b></th>
              </tr>
            </thead>
            <tbody>';

  return $varHTML;
}

function getUserLogRptHeader( $fromDateIn, $toDateIn, $userEmail) {
  global $namesConfigData;

  $varHTML='';
  $reportGeneratedBy = 'Auto Generated by System';

  $dateObj = new DateTime($fromDateIn);
  $fromDateIn = $dateObj->format(REPORT_DATE_FORMAT);

  $dateObj = new DateTime($toDateIn);
  $toDateIn = $dateObj->format(REPORT_DATE_FORMAT);

  if ( $userEmail != '' ){
      $reportGeneratedBy=$userEmail;
  }

  $companyName = $namesConfigData['company']['companyName'];
  $varHTML =  '<!DOCTYPE html><html><head><style>table {
      border-collapse: collapse;
      width: 100%;
      }
      th, td {
        border: 1px solid #ccc; 
        padding: 6px;
      }
      </style>
      </head>
      <body><div><table cellspacing="0" cellpadding="2" border="1" style="width:100%; "><thead>
            <tr style="background-color: '.REPORT_HEADER_COLOR.';">
            <td colspan="4" style="color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.'; text-align: center;"><b>'.USER_LOG_REPORT_NAME.'</b></td>
          </tr></thead>
          <tbody>
        <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
                <td width="20%">Organization Name</td>
                <td width="32%">'.$companyName.'</td>
                <td width="22%">From Date</td>
                <td width="26%">'.$fromDateIn.'</td>
              </tr>
              <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
                <td colspan="2" rowspan="3" ></td>
                <td >To Date</td>
                <td >'.$toDateIn.'</td>
              </tr>
                <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
                <td >Report Taken By</td>
                <td >'.$reportGeneratedBy.'</td>
              </tr>
              <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
                <td >Report Date & Time</td>
                <td >'.date(REPORT_DATE_TIME_FORMAT).'</td>
              </tr>
            </tbody>
            </table></div>';

    $varHTML .=  '<div><table cellspacing="0" cellpadding="2" border="1" style="width:100%; ">
            <thead>
              <tr style="background-color: green;">
              <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.';" width="20%" ><b>Date and Time</b></th>
                <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="40%"><b>Email</b></th>
                <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; " width="40%"><b>Action</b></th>
              </tr>
            </thead>
            <tbody>';

  return $varHTML;
}


function getFirmwareVersionRptHeader( $userEmail) {
  global $namesConfigData;

  $varHTML='';
  $reportGeneratedBy = 'Auto Generated by System';

  if ( $userEmail != '' ){
      $reportGeneratedBy=$userEmail;
  }

  $companyName = $namesConfigData['company']['companyName'];
  $varHTML =  '<!DOCTYPE html><html><head><style>table {
      border-collapse: collapse;
      width: 100%;
      }
      th, td {
        border: 1px solid #ccc; 
        padding: 6px;
      }
      </style>
      </head>
      <body><div><table cellspacing="0" cellpadding="2" border="1" style="width:100%; "><thead>
            <tr style="color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.';">
            <td colspan="4" style="color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.'; color='.REPORT_HEADER_FONT_COLOR.'; text-align: center;"><b>'.FIRMWARE_VERSION_REPORT_NAME.'</b></td>
          </tr></thead>
          <tbody>
        <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
                <td >Organization Name</td>
                <td >'.$companyName.'</td>
                <td >Report Taken By</td>
                <td >'.$reportGeneratedBy.'</td>
              </tr>
              <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
                <td colspan="2"></td>
                <td >Report Date & Time</td>
                <td >'.date(REPORT_DATE_TIME_FORMAT).'</td>
              </tr>
            </tbody>
            </table></div>';

    $varHTML .=  '<div><table cellspacing="0" cellpadding="2" border="1" style="width:100%; ">
            <thead>
              <tr style="color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.';">
                <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; color='.REPORT_HEADER_FONT_COLOR.'; " ><b>Date and Time</b></th>
                <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; color='.REPORT_HEADER_FONT_COLOR.'; " ><b>State</b></th>
                <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; color='.REPORT_HEADER_FONT_COLOR.'; " ><b>Branch</b></th>
                <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; color='.REPORT_HEADER_FONT_COLOR.'; " ><b>Facility</b></th>
                <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; color='.REPORT_HEADER_FONT_COLOR.'; " ><b>Building</b></th>
                <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; color='.REPORT_HEADER_FONT_COLOR.'; " ><b>Floor</b></th>
                <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; color='.REPORT_HEADER_FONT_COLOR.'; " ><b>Zone</b></th>
                <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; color='.REPORT_HEADER_FONT_COLOR.'; " ><b>Device Name</b></th>
                <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; color='.REPORT_HEADER_FONT_COLOR.'; " ><b>Model No</b></th>
                <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; color='.REPORT_HEADER_FONT_COLOR.'; " ><b>Firmware Version</b></th>
                <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; color='.REPORT_HEADER_FONT_COLOR.'; " ><b>User</b></th>
                <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; color='.REPORT_HEADER_FONT_COLOR.'; " ><b>Status</b></th>
              </tr>
            </thead>
            <tbody>';

  return $varHTML;
}


function getAlarmsRptHeader($zoneID, $deviceID, $fromDateIn, $toDateIn, $userEmail) {
  global $sensorConfigData;
  global $deviceConfigData;
  global $namesConfigData;

  $varHTML='';
  $reportGeneratedBy = 'Auto Generated by System';

  $dateObj = new DateTime($fromDateIn);
  $fromDateIn = $dateObj->format(REPORT_DATE_FORMAT);

  $dateObj = new DateTime($toDateIn);
  $toDateIn = $dateObj->format(REPORT_DATE_FORMAT);

  if ( $userEmail != '' ){
      $reportGeneratedBy=$userEmail;
  }

  $companyName = $namesConfigData['company']['companyName'];
  $deviceName='';
  $rowspan="3";
  if($deviceID != '') {
    $locationName = $namesConfigData['locations'][$deviceConfigData[$deviceID]['locationID']]['locationName'];
    $branchName = $namesConfigData['branches'][$deviceConfigData[$deviceID]['branchID']]['branchName'];
    $facilityName = $namesConfigData['facilities'][$deviceConfigData[$deviceID]['facilityID']]['facilityName'];
    $buildingName = $namesConfigData['buildings'][$deviceConfigData[$deviceID]['buildingID']]['buildingName'];
    $floorName = $namesConfigData['floors'][$deviceConfigData[$deviceID]['floorID']]['floorName'];
    $zoneName = $namesConfigData['zones'][$deviceConfigData[$deviceID]['zoneID']]['zoneName'];
    $deviceName = $deviceConfigData[$deviceID]['deviceName'];
    $rowspan="4";
  }
  else {
    //get values based on zoneid;
    $locationID = $namesConfigData['zones'][$zoneID]['locationID'];
    $branchID = $namesConfigData['zones'][$zoneID]['branchID'];
    $facilityID = $namesConfigData['zones'][$zoneID]['facilityID'];
    $buildingID = $namesConfigData['zones'][$zoneID]['buildingID'];
    $floorID = $namesConfigData['zones'][$zoneID]['floorID'];

    $locationName = $namesConfigData['locations'][$locationID]['locationName'];
    $branchName = $namesConfigData['branches'][$branchID]['branchName'];
    $facilityName = $namesConfigData['facilities'][$facilityID]['facilityName'];
    $buildingName = $namesConfigData['buildings'][$buildingID]['buildingName'];
    $floorName = $namesConfigData['floors'][$floorID]['floorName'];
    $zoneName = $namesConfigData['zones'][$zoneID]['zoneName'];
    $rowspan="4";
  }

  
  $varHTML =  '<!DOCTYPE html><html><head><style>table {
    border-collapse: collapse;
    width: 100%;
    }
    th, td {
      border: 1px solid #ccc; 
      padding: 6px;
    }
    </style>
    </head>
    <body><div><table cellspacing="0" cellpadding="2" border="1" style="width:100%; "><thead>
          <tr style="color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.';">
          <td colspan="4" style="color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.'; text-align: center;"><b>'.ALARMS_REPORT_NAME.'</b></td>
        </tr></thead>
        <tbody>
      <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
              <td width="20%" >Organization Name</td>
              <td width="32%" >'.$companyName.'</td>
              <td width="22%">From Date</td>
              <td width="26%">'.$fromDateIn.'</td>
            </tr>
            <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
              <td >Location</td>
              <td >'.$locationName.'</td>
              <td >To Date</td>
              <td >'.$toDateIn.'</td>
            </tr>
              <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
              <td >Branch</td>
              <td >'.$branchName.'</td>
              <td >Report Taken By</td>
              <td >'.$reportGeneratedBy.'</td>
            </tr>
            <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
              <td >Facility</td>
              <td >'.$facilityName.'</td>
              <td >Report Date & Time</td>
              <td >'.date(REPORT_DATE_TIME_FORMAT).'</td>
            </tr>
            <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
              <td >Building</td>
              <td >'.$buildingName.'</td>
              <td colspan="2" rowspan="'.$rowspan.'"></td>
            </tr>
            <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
              <td >Floor</td>
              <td >'.$floorName.'</td>
            </tr>
            <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
              <td >Zone</td>
              <td >'.$zoneName.'</td>
            </tr>';
            if ($deviceID != '') {
              $varHTML .=  '<tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
              <td >Device</td>
              <td >'.$deviceName.'</td>
              </tr>';
            }
            $varHTML .= '</tbody></table></div>';

          $varHTML .=  '<div><table cellspacing="0" cellpadding="2" border="1" style="width:100%; ">
          <thead>
            <tr style="color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.';">
              <th style=" text-align: center;" width="15%"><b>From & To Date Time</b></th>
              <th style=" text-align: center;" width="8%"><b>Duration HH:MM</b></th>
              <th style=" text-align: center;" width="10%"><b>Devices</b></th>
              <th style=" text-align: center;" width="10%"><b>Sensor Tag</b></th>
              <th style=" text-align: center;" width="6%"><b>Value</b></th>
              <th style=" text-align: center;" width="9%"><b>Alert Type</b></th>
              <th style=" text-align: center;" width="17%" ><b>Message</b></th>
              <th style=" text-align: center;" width="17%"><b>Reason</b></th>
              <th style=" text-align: center;" width="8%"><b>User</b></th>
            </tr>
          </thead>
          <tbody>';

          return $varHTML;
}

function getApplicationVersionRptHeader( $userEmail) {
  global $namesConfigData;

  $varHTML='';
  $reportGeneratedBy = 'Auto Generated by System';

  if ( $userEmail != '' ){
      $reportGeneratedBy=$userEmail;
  }

  $companyName = $namesConfigData['company']['companyName'];
  $varHTML =  '<!DOCTYPE html><html><head><style>table {
      border-collapse: collapse;
      width: 100%;
      }
      th, td {
        border: 1px solid #ccc; 
        padding: 6px;
      }
      </style>
      </head>
      <body><div><table cellspacing="0" cellpadding="2" border="1" style="width:100%; "><thead>
            <tr style="color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.';">
            <td colspan="4" style="color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.'; color:'.REPORT_HEADER_FONT_COLOR.'; text-align: center;"><b>'.APPLICATION_VERSION_REPORT_NAME.'</b></td>
          </tr></thead>
          <tbody>
        <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_ONE.';">
                <td width="20%">Organization Name</td>
                <td width="32%">'.$companyName.'</td>
                <td  width="22%">Report Taken By</td>
                <td width="26%">'.$reportGeneratedBy.'</td>
              </tr>
              <tr style="background-color: '.REPORT_ALTERNATIVE_ROW_COLOR_TWO.';">
                <td colspan="2"></td>
                <td >Report Date & Time</td>
                <td >'.date(REPORT_DATE_TIME_FORMAT).'</td>
              </tr>
            </tbody>
            </table></div>';

    $varHTML .=  '<div><table cellspacing="0" cellpadding="2" border="1" style="width:100%; ">
            <thead>
              <tr style="color: '.REPORT_HEADER_FONT_COLOR.'; background-color: '.REPORT_HEADER_COLOR.';">
                <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; color:'.REPORT_HEADER_FONT_COLOR.'; " ><b>Date and Time</b></th>
                <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; color:'.REPORT_HEADER_FONT_COLOR.';" ><b>Version Number</b></th>
                <th style="color: '.REPORT_HEADER_FONT_COLOR.'; text-align: center; background-color: '.REPORT_HEADER_COLOR.'; color:'.REPORT_HEADER_FONT_COLOR.';" ><b>Summary</b></th>
              </tr>
            </thead>
            <tbody>';

  return $varHTML;
}



?>